LLVM_OR_MLIR_LIBS := \
  LLVMAggressiveInstCombine \
  LLVMAMDGPUAsmParser \
  LLVMAMDGPUCodeGen \
  LLVMAMDGPUDesc \
  LLVMAMDGPUInfo \
  LLVMAMDGPUUtils \
  LLVMAnalysis \
  LLVMAsmParser \
  LLVMAsmPrinter \
  LLVMBinaryFormat \
  LLVMBitReader \
  LLVMBitWriter \
  LLVMBitstreamReader \
  LLVMCFGuard \
  LLVMCodeGen \
  LLVMCodeGenTypes \
  LLVMCore \
  LLVMCoroutines \
  LLVMDebugInfoCodeView \
  LLVMDebugInfoDWARF \
  LLVMDemangle \
  LLVMExecutionEngine \
  LLVMFrontendOffloading \
  LLVMFrontendOpenMP \
  LLVMGlobalISel \
  LLVMHipStdPar \
  LLVMInstrumentation \
  LLVMLinker \
  LLVMipo \
  LLVMInstCombine \
  LLVMIRPrinter \
  LLVMIRReader \
  LLVMJITLink \
  LLVMMC \
  LLVMMCDisassembler \
  LLVMMCParser \
  LLVMMIRParser \
  LLVMNVPTXCodeGen \
  LLVMNVPTXDesc \
  LLVMNVPTXInfo \
  LLVMObjCARCOpts \
  LLVMObject \
  LLVMOption \
  LLVMOrcJIT \
  LLVMOrcShared \
  LLVMOrcTargetProcess \
  LLVMPasses \
  LLVMProfileData \
  LLVMRemarks \
  LLVMRuntimeDyld \
  LLVMScalarOpts \
  LLVMSelectionDAG \
  LLVMSupport \
  LLVMTarget \
  LLVMTargetParser \
  LLVMTextAPI \
  LLVMTransformUtils \
  LLVMVectorize \
  LLVMX86AsmParser \
  LLVMX86CodeGen \
  LLVMX86Desc \
  LLVMX86Info \
  LLVMWindowsDriver \
  MLIRAffineAnalysis \
  MLIRAffineDialect \
  MLIRAffineToStandard \
  MLIRAffineTransforms \
  MLIRAffineUtils \
  MLIRAnalysis \
  MLIRArithAttrToLLVMConversion \
  MLIRArithDialect \
  MLIRArithToLLVM \
  MLIRArithUtils \
  MLIRAsmParser \
  MLIRBufferizationDialect \
  MLIRBuiltinToLLVMIRTranslation \
  MLIRBytecodeReader \
  MLIRCallInterfaces \
  MLIRCastInterfaces \
  MLIRComplexDialect \
  MLIRControlFlowDialect \
  MLIRControlFlowInterfaces \
  MLIRControlFlowToLLVM \
  MLIRControlFlowToSCF \
  MLIRDataLayoutInterfaces \
  MLIRDestinationStyleOpInterface \
  MLIRDialect \
  MLIRDialectUtils \
  MLIRDLTIDialect \
  MLIRExecutionEngine \
  MLIRExecutionEngineUtils \
  MLIRFuncDialect \
  MLIRFuncAllExtensions \
  MLIRFuncInlinerExtension \
  MLIRFunctionInterfaces \
  MLIRFuncToLLVM \
  MLIRGPUDialect \
  MLIRGPUToGPURuntimeTransforms \
  MLIRGPUToNVVMTransforms \
  MLIRGPUTransforms \
  MLIRIndexDialect \
  MLIRInferIntRangeCommon \
  MLIRInferIntRangeInterface \
  MLIRInferTypeOpInterface \
  MLIRIR \
  MLIRLLVMCommonConversion \
  MLIRLLVMDialect \
  MLIRLLVMIRTransforms \
  MLIRLLVMToLLVMIRTranslation \
  MLIRLoopLikeInterface \
  MLIRMaskableOpInterface \
  MLIRMaskingOpInterface \
  MLIRMathDialect \
  MLIRMathToLLVM \
  MLIRMemorySlotInterfaces \
  MLIRMemRefDialect \
  MLIRMemRefToLLVM \
  MLIRMemRefUtils \
  MLIRNVVMDialect \
  MLIRNVVMToLLVMIRTranslation \
  MLIRParallelCombiningOpInterface \
  MLIRParser \
  MLIRPass \
  MLIRPDLDialect \
  MLIRPDLInterpDialect \
  MLIRPDLToPDLInterp \
  MLIRPresburger \
  MLIRRewrite \
  MLIRRewritePDL \
  MLIRSCFDialect \
  MLIRSCFToControlFlow \
  MLIRShapedOpInterfaces \
  MLIRSideEffectInterfaces \
  MLIRSparseTensorDialect \
  MLIRSupport \
  MLIRTargetLLVMIRExport \
  MLIRTensorDialect \
  MLIRTransforms \
  MLIRTransformUtils \
  MLIRUBDialect \
  MLIRValueBoundsOpInterface \
  MLIRVectorDialect \
  MLIRVectorInterfaces \
  MLIRVectorToLLVM \
  MLIRVectorTransforms \
  MLIRViewLikeInterface
